---
- name: Set up Katello
  hosts: all
  tasks: 
  
    - name: Check if repo enabled
      shell: hammer repository list
      register: repositories_enabled
      become: true
    
    - name: Enable Repos
      shell: > 
         hammer repository-set enable  
         --organization "Default Organization" 
         --product "Red Hat Enterprise Linux Server" 
         --name "Red Hat Enterprise Linux 7 Server (Kickstart)" 
         --releasever "7Server" 
         --basearch "x86_64"
      environment:
         SHELL: /bin/bash
      when:  repositories_enabled.stdout.find('Red Hat Enterprise Linux 7 Server Kickstart x86_64 7Server') == -1
      become: true
     
      
  
  
  
